### PR TITLE
fix: Update signupText and signinText to logos

### LINKED ISSUE #141: Update oidc config

### PR DESCRIPTION
**Pull request by talwinder50**
Change tested in local wallet 
Screen Shot 2021-12-21 at 1 13 17 PM

Screen Shot 2021-12-21 at 1 13 09 PM
closes #141

Signed-off-by: talwinder50 <talwinderkaur50@gmail.com>

### CODE REVIEW

File: cmd/auth-rest/startcmd/parameters.go [hunk 1]
```diff
@@ -56,9 +56,9 @@ type oidcProviderConfig struct {
 	ClientID     string `yaml:"clientID"`
 	ClientSecret string `yaml:"clientSecret"`
 	Name         string `yaml:"name"`
-	SignUpText   string `yaml:"signUpText"`
-	SignInText   string `yaml:"signInText"`
-	LogoURL      string `yaml:"logoURL"`
+	SignUpLogo   string `yaml:"signUpLogo"`
+	SignInLogo   string `yaml:"signInLogo"`
+	Order        string `yaml:"order"`
```
Comment (rolsonquadras) [inline cmd/auth-rest/startcmd/parameters.go:61]: Should this be an int ?

File: cmd/auth-rest/startcmd/parameters.go [hunk 2]
```diff
@@ -56,9 +56,9 @@ type oidcProviderConfig struct {
 	ClientID     string `yaml:"clientID"`
 	ClientSecret string `yaml:"clientSecret"`
 	Name         string `yaml:"name"`
-	SignUpText   string `yaml:"signUpText"`
-	SignInText   string `yaml:"signInText"`
-	LogoURL      string `yaml:"logoURL"`
+	SignUpLogo   string `yaml:"signUpLogo"`
+	SignInLogo   string `yaml:"signInLogo"`
```
Comment (rolsonquadras) [inline cmd/auth-rest/startcmd/parameters.go:60]: Can we add prefix URL ? since this is pointing to an url

**Review by rolsonquadras — APPROVED** [review]

**Review by sudeshrshetty — APPROVED** [review]
